#include "Side_dish.h"

Side_dish::Side_dish(){
	name.push_back("Èò¹ä");
	attribute.push_back('C');
	calories.push_back(250);
	name.push_back("ººÀ½¹ä");
	attribute.push_back('C');
	calories.push_back(617);
	name.push_back("¼öÁ¦ºñ");
	attribute.push_back('C');
	calories.push_back(200);
	name.push_back("¹èÃß±èÄ¡");
	attribute.push_back('C');
	calories.push_back(80);
	name.push_back("Ä®±¹¼ö");
	attribute.push_back('C');
	calories.push_back(545);
	
	name.push_back("¾ËÅÁ");
	attribute.push_back('P');
	calories.push_back(439);
	name.push_back("¼ø´ë");
	attribute.push_back('P');
	calories.push_back(274);
	name.push_back("ºØ¾î»§");
	attribute.push_back('P');
	calories.push_back(200);
	name.push_back("ºÒ°í±â");
	attribute.push_back('P');
	calories.push_back(685);
	name.push_back("°¥Ä¡±¸ÀÌ");
	attribute.push_back('P');
	calories.push_back(556);

	name.push_back("¸ÓÇÉ");
	attribute.push_back('F');
	calories.push_back(301);
	name.push_back("¾Æ¸óµå");
	attribute.push_back('F');
	calories.push_back(40);
	name.push_back("»ï°ã»ì");
	attribute.push_back('F');
	calories.push_back(417);
	name.push_back("´ß´Ù¸®");
	attribute.push_back('F');
	calories.push_back(211);
	name.push_back("ÅÁ¼öÀ°");
	attribute.push_back('F');
	calories.push_back(616);
	name.push_back("°íµî¾î±¸ÀÌ");
	attribute.push_back('F');
	calories.push_back(532);

	name.push_back("¹Ù³ª³ª");
	attribute.push_back('M');
	calories.push_back(80);
	name.push_back("µÈÀåÂî°Ô");
	attribute.push_back('M');
	calories.push_back(128);
	name.push_back("¸êÄ¡ººÀ½");
	attribute.push_back('M');
	calories.push_back(96);
	name.push_back("µ¿ÅÂÂî°Ô");
	attribute.push_back('M');
	calories.push_back(224);
	name.push_back("½ºÆÄ°ÔÆ¼");
	attribute.push_back('M');
	calories.push_back(690);
}
Side_dish::~Side_dish(){

}